# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Pagination"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  _componentId: pagination-29269ce3-a589-4f1d-8679-699b568d7dd1
  pagination:
  color_group: primary

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
