# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Cards"
  description: "Display a grid of items (posts, services, custom items)"
  icon: "view_module"
  tags: ["cards", "grid", "blog", "services"]

# Defines the structure of this component, as well as the default values
blueprint:
  _componentId: cards-0b30a011-3cf9-4ddd-b65b-e7e6d5869c0c
  source: "manual"
  cardStyle: "standard"
  columns: 3
  content:
    eyebrow: "Our Work"
    headline: "Latest Updates"
    description: "Check out our latest news and projects."
    items:
      - title: "Card Title 1"
        description: "Description for card 1"
        image: bookshop:structure:imgvid
        url: "#"
      - title: "Card Title 2"
        description: "Description for card 2"
        image: bookshop:structure:imgvid
        url: "#"
      - title: "Card Title 3"
        description: "Description for card 3"
        image: bookshop:structure:imgvid
        url: "#"
  styles:
    color_group: "primary"
    textAlignment: "center"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  source: "manual"
  cardStyle: "standard"
  columns: 3
  content:
    eyebrow: "Preview"
    headline: "Card Grid"
    description: "A grid of cards."
    items:
      - title: "Sample Card 1"
        description: "This is a sample card description."
        image:
          _bookshop_name: generic/image
          imagePath: "https://via.placeholder.com/400x300"
          imageAlt: "Placeholder"
        url: "#"
      - title: "Sample Card 2"
        description: "This is a sample card description."
        image:
          _bookshop_name: generic/image
          imagePath: "https://via.placeholder.com/400x300"
          imageAlt: "Placeholder"
        url: "#"
      - title: "Sample Card 3"
        description: "This is a sample card description."
        image:
          _bookshop_name: generic/image
          imagePath: "https://via.placeholder.com/400x300"
          imageAlt: "Placeholder"
        url: "#"
  styles:
    color_group: "primary"
    textAlignment: "center"

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  source:
    type: select
    options:
      values:
        - label: "Manual Items"
          value: "manual"
        - label: "Blog Posts"
          value: "blog"
        - label: "Services"
          value: "services"
        - label: "Happenings"
          value: "happenings"
  cardStyle:
    type: select
    options:
      values:
        - label: "Standard"
          value: "standard"
        - label: "Minimal"
          value: "minimal"
        - label: "Featured (First item large)"
          value: "featured"
        - label: "Profile"
          value: "profile"
  columns:
    type: select
    options:
      values:
        - label: "2 Columns"
          value: 2
        - label: "3 Columns"
          value: 3
        - label: "4 Columns"
          value: 4
  content:
    items:
      hidden: "source != 'manual'"
