# Metadata about this component, to be used in the CMS
spec:
  structures:
    - hero_blocks
  label: "Banner Image Hero"
  description: A simple hero section with image as banner
  icon: feed
  tags: []
  tabbed: true

# Defines the structure of this component, as well as the default values
blueprint:
  _componentId: bannerHero-572788f2-29c0-43e7-84da-08b63db954f6
  content:
    sectionId:
    heading: bookshop:generic/heading!
    backgroundImage: bookshop:generic/image
  styles:
    color_group: primary
    backgroundOpacity: 50

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  backgroundOpacity:
    type: range
    options:
      min: 0
      max: 100
      step: 5
      default: 50
    comment: Set the opacity percentage of the background
