# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
    - extra_blocks
  label: "Image Carousel"
  description: "Show off your portfolio in a clean, organized layout, perfect for showcasing collections, portfolios, or visual highlights."
  icon: view_carousel
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  _componentId: imageCarousel-3c829311-df32-41c0-a254-9e0f1afccf29
  content:
    showNote: true
    sectionId:
    heading: bookshop:structure:headingBlocks
    images: [bookshop:generic/image]
  styles:
    color_group: primary


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
