# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Editorial Content"
  tabbed: true
  description: A rich editing experience with call outs, quotes, and more.
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    sectionId:
    heading: bookshop:structure:headingBlocks
    editorials: [bookshop:structure:editorial_blocks!(generic/textBlock)]
  styles:
    color_group: primary

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
