# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
    - extra_blocks
  label: "Hero Section"
  description: Hero section with title, subtitle, description, and call-to-action buttons
  icon: view_headline
  tags: [alpha]

# Defines the structure of this component, as well as the default values
blueprint:
  _componentId: hero-19d85fcb-125b-470e-810b-682275114bda
  content:
    label:
    sectionId:
    badge:
    heading: "Welcome to Our Site"
    subheading:
    description: "A compelling description that captures your value proposition and engages visitors."
    buttons:
    image:
      source:
      alt:
  styles:
    color_group: primary
    layout: centered
    backgroundImage:
      source:
      alt:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  content:
    badge: "New Release"
    heading: "Build Something Amazing"
    subheading: "The future is here"
    description: "Create beautiful, responsive websites with our powerful component library. Start building today."
    buttons:
      - _bookshop_name: building-blocks/core-elements/button
        content:
          text: "Get Started"
          link: "#"
        styles:
          variant: normal
          size: md
      - _bookshop_name: building-blocks/core-elements/button
        content:
          text: "Learn More"
          link: "#"
        styles:
          variant: ghost
          size: md
    image:
      source: /images/tree.jpg
      alt: Hero image
  styles:
    color_group: primary
    layout: centered

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  label:
    type: text
    label: Label
    comment: Optional label to identify this section in the editor
  sectionId:
    type: text
    label: Section ID
    comment: Anchor ID for linking to this section
  badge:
    type: text
    label: Badge Text
    comment: Optional small badge/label above the heading
  heading:
    type: text
    label: Heading
    comment: Main headline of the hero section
  subheading:
    type: text
    label: Subheading
    comment: Optional smaller heading below the main heading
  description:
    type: markdown
    label: Description
    comment: Supporting text that describes your value proposition
  buttons:
    type: array
    label: Buttons
    comment: Call-to-action buttons
    options:
      structures: _structures.button_items
  image:
    type: object
    label: Hero Image
    comment: Image for split layout (used when layout is set to split)
    hidden: "styles.layout !== 'split-left' && styles.layout !== 'split-right'"
  image.source:
    type: image
    label: Image
  image.alt:
    type: text
    label: Alt Text
  color_group:
    type: select
    label: Color Theme
    comment: Color scheme for the section
    options:
      allow_empty: false
      value_key: id
      preview:
        text:
          - key: name
        icon:
          - key: icon
      values: data.theme..[?(@.primaryColor)]
  layout:
    type: select
    label: Layout
    comment: How the hero content is arranged
    options:
      values:
        - name: Centered
          id: centered
        - name: Left Aligned
          id: left
        - name: Split (Image Left)
          id: split-left
        - name: Split (Image Right)
          id: split-right
  backgroundImage:
    type: object
    label: Background Image
    options:
      preview:
        text: Background Image
        subtext:
          key: source
  backgroundImage.source:
    type: image
    label: Image
  backgroundImage.alt:
    type: text
    label: Alt Text
