# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
    - extra_blocks
  label: "Review Cards"
  description: Straight forward reviews
  icon: reviews
  tags: [review, connected]
  tabbed: true

# Defines the structure of this component, as well as the default values
blueprint:
  _componentId: reviewCards-e9ca074f-936e-4ba6-ba53-c94ee8c1d42b
  content:
    sectionId:
    heading: bookshop:structure:headingBlocks
    usePersonImage: false
    reviews:
      - review:
        card_color_group: primary
        colorFromGroup: background
  styles:
    color_group: primary

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  review:
    type: select
    options:
      values: data.reviews
      value_key: id
      text_key: name