# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
    - extra_blocks
  label: "Side by Side Section"
  description: Two-column split layout with text and media content
  icon: view_column
  tags: [alpha]
  tabbed: true

# Defines the structure of this component, as well as the default values
blueprint:
  _componentId: side-by-side-0d084dab-33f8-40d5-947b-739e8ec27e8a
  content:
    label:
    sectionId:
    badge:
    heading: "Why Choose Us"
    description: "We provide exceptional service and quality products that exceed expectations."
    buttons:
    image:
      source:
      alt:
  styles:
    color_group: primary
    layout: image-right
    backgroundImage:
      source:
      alt:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  content:
    badge: "About Us"
    heading: "Building the Future Together"
    description: "We're passionate about creating tools that help people succeed. Our team works tirelessly to deliver the best possible experience for our users."
    buttons:
      - _bookshop_name: building-blocks/core-elements/button
        content:
          text: "Get Started"
          link: "#"
        styles:
          variant: normal
          size: md
      - _bookshop_name: building-blocks/core-elements/button
        content:
          text: "Learn More"
          link: "#"
        styles:
          variant: ghost
          size: md
    image:
      source: /images/tree.jpg
      alt: Team working together
  styles:
    color_group: primary
    layout: image-right

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  label:
    type: text
    label: Label
    comment: Optional label to identify this section in the editor
  sectionId:
    type: text
    label: Section ID
    comment: Anchor ID for linking to this section
  badge:
    type: text
    label: Badge Text
    comment: Optional small badge/label above the heading
  heading:
    type: text
    label: Heading
    comment: Main headline
  description:
    type: markdown
    label: Description
    comment: Supporting text content
  buttons:
    type: array
    label: Buttons
    comment: Action buttons
    options:
      structures: _structures.button_items
  image:
    type: object
    label: Image
    comment: Featured image for the media column
  image.source:
    type: image
    label: Image
  image.alt:
    type: text
    label: Alt Text
  color_group:
    type: select
    label: Color Theme
    comment: Color scheme for the section
    options:
      allow_empty: false
      value_key: id
      preview:
        text:
          - key: name
        icon:
          - key: icon
      values: data.theme..[?(@.primaryColor)]
  layout:
    type: select
    label: Layout
    comment: Position of image relative to text
    options:
      values:
        - name: Image Left
          id: image-left
        - name: Image Right
          id: image-right
  backgroundImage:
    type: object
    label: Background Image
    options:
      preview:
        text: Background Image
        subtext:
          key: source
  backgroundImage.source:
    type: image
    label: Image
  backgroundImage.alt:
    type: text
    label: Alt Text
