# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Scattered Images Gallery"
  description: An image gallery where the images are scattered randomly
  icon:
  tags: []
  tabbed: true

# Defines the structure of this component, as well as the default values
blueprint:
  _componentId: scatterGallery-e67d93a5-7ea1-4230-990b-72427ef2f030
  content:
    showNote: true
    sectionId:
    heading: bookshop:structure:headingBlocks
    images: [bookshop:generic/image]
    buttons: [bookshop:structure:buttons]
  styles:
    color_group: primary
    galleryStyling:
      imageModal: true
      photoSize: 500
      borderSize: 10
      arstr: "1"
      showInfo: false
      infoStyle: "1"
      autoSlide: false
      duration: 2


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  imageModal:
    comment: "If true, the selected image will open in a modal (made bigger) when clicked"
  photoSize:
    comment: "The size of the image in pixels"
  borderSize:
    comment: "The size of the border in pixels. This gives the images a polaroid look. 0 for no border. "
  arstr:
    comment: "The scattering effect of the images."
    type: select
    options:
      value_key: id
      values:
        - id: "1"
          name: Scattered
        - id: "2"
          name: Straight
        - id: "3"
          name: Scattered 3D
        - id: "4"
          name: Straight 3D
  showInfo:
    comment: "If true, the image alt text will be shown"
  infoStyle:
    comment: "The style of the image alt text."
    type: select
    options:
      value_key: id
      values:
        - id: "1"
          name: Under
        - id: "2" 
          name: Part of the image
        - id: "3" 
          name: Overlay
  autoSlide:
    comment: "If true, the images will automatically slide. This always gets turned off if someone manually selects and image or slides the gallery"
  duration:
    comment: "The duration of the slide in seconds"
