# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_sections
  label: "Spacer"
  description: Empty vertical spacing element
  icon: unfold_more
  tags: [alpha]

# Defines the structure of this component, as well as the default values
blueprint:
  _componentId: spacer-9f3a1b2c-33d9-477a-9ab5-27ae7f0fbbd1
  size: md
  responsiveSize:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  size:
    type: select
    label: Size
    comment: Height of the spacer
    options:
      values:
        - name: Extra Small (8px)
          id: xs
        - name: Small (16px)
          id: sm
        - name: Medium (32px)
          id: md
        - name: Large (48px)
          id: lg
        - name: Extra Large (64px)
          id: xl
        - name: 2XL (96px)
          id: 2xl
        - name: 3XL (128px)
          id: 3xl
  responsiveSize:
    type: select
    label: Mobile Size
    comment: Optional smaller size on mobile devices
    options:
      values:
        - name: Same as Desktop
          id:
        - name: Extra Small (8px)
          id: xs
        - name: Small (16px)
          id: sm
        - name: Medium (32px)
          id: md
        - name: Large (48px)
          id: lg
