# Metadata about this component, to be used in the CMS
spec:
  structures:
    - hero_blocks
  label: "Big Text Hero"
  description: "Hero section with a big text heading"
  icon:
  tags: []
  tabbed: true

# Defines the structure of this component, as well as the default values
blueprint:
  _componentId: bigTextHero-b40d6431-50a9-4c35-8045-0513fa07bc44
  content:
    sectionId:
    heading: bookshop:generic/bigText
    image: bookshop:structure:imgvid
  styles:
    color_group: primary
    colorFromGroup: white
    backgroundOpacity: 50
    verticalAlignment: top

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  image:
    label: Media
  backgroundOpacity:
    type: range
    options:
      min: 0
      max: 100
      step: 5
      default: 50
    comment: Set the opacity percentage of the background
  colorFromGroup:
    type: select
    options:
      allow_empty: false
      value_key: id
      values:
        - id: white
          name: White
        - id: diff
          name: Difference
        - id: text
          name: Text
        - id: background
          name: Background
        - id: primary
          name: Primary
        - id: secondary
          name: Secondary
        - id: accent
          name: Accent
  verticalAlignment:
    type: select
    options:
      allow_empty: false
      value_key: id
      values:
        - id: top
          name: Top
        - id: middle
          name: Middle
        - id: bottom
          name: Bottom