# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "LightBox"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  _componentId: lightBox-80a8152a-35d0-4766-935a-13677a057e1f
  id:
  images: [bookshop:generic/image]
  
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
