# Metadata about this component, to be used in the CMS
spec:
  structures:
    #- hero_blocks
  label: "Image overlap Text"
  description: This is a custom section that needs to be developed just for your business.
  icon:
  tags: []
  tabbed: true

# Defines the structure of this component, as well as the default values
blueprint:
  _componentId: overlapHero-a6b07e09-a318-4421-b350-f3d54654a169
  content:
    sectionId:
    backgroundImage: bookshop:generic/image
    foregroundImage: bookshop:generic/image
    buttons: [bookshop:structure:buttons]
  styles:
    color_group: primary
    backgroundOpacity: 50

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
