# Metadata about this component, to be used in the CMS
spec:
  structures:
    - buttons
  label: "Modal Button"
  description:
  icon: open_in_full
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  _componentId: modalButton-ce57d451-a7dc-4222-9ef8-c7536c294970
  id:
  resource: bookshop:structure:resource
  form_color_group: primary
  text: "Button text"
  color_group: primary
  colorFromGroup: primary
  ghostButton: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  id:
    hidden: true
  resource:
    comment: 'To what should the pop up open to?'
  form_color_group:
    comment: "This only applies if you choose a form as the resource, else it does nothing"