# Metadata about this component, to be used in the CMS
spec:
  structures:
    - form_blocks
  label: "Form Simple Text"
  description: A simple text block for use in a form
  icon: edit_note
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  _componentId: simpleText-b6172947-286c-4be1-907f-4f7d08c987a8
  text: Description text to compliment the form

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  text:
    type: textarea