# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Pagination"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  _componentId: pagination-d525ae3f-25c7-4849-9c94-f5e07c275598
  pagination:
  color_group: primary

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
