# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_sections
    - media
    - imgvid
  label: "Video"
  description: Embedded video from YouTube, Vimeo, or local source
  icon: play_circle
  tags: [alpha]

# Defines the structure of this component, as well as the default values
blueprint:
  _componentId: video-11b8c88f-1e7f-4e16-82c0-1a45c614762f
  type: youtube
  id:
  title:
  source:
  thumbnail:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  type:
    type: select
    label: Video Type
    comment: Where the video is hosted
    options:
      values:
        - name: YouTube
          id: youtube
        - name: Vimeo
          id: vimeo
        - name: Local File
          id: local-source
  id:
    type: text
    label: Video ID
    comment: The YouTube or Vimeo video ID (found in the URL)
    hidden: type == "local-source"
  title:
    type: text
    label: Video Title
    comment: Accessibility title for the video (shown on hover)
    hidden: type == "local-source"
  source:
    type: file
    label: Video File
    comment: Local video file (MP4 recommended)
    hidden: type != "local-source"
  thumbnail:
    type: image
    label: Thumbnail
    comment: Preview image shown before video plays
    hidden: type != "local-source"
