# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_sections
  label: "Pagination"
  description: Page navigation for collections and lists
  icon: navigate_before
  tags: [alpha]
  tabbed: true

# Defines the structure of this component, as well as the default values
blueprint:
  _componentId: pagination-fa7e6d70-ad8c-4128-bb1f-a2905352d2d7
  content:
    previousUrl:
    nextUrl:
    previousLabel: Previous
    nextLabel: Next
    currentPage: 1
    totalPages: 1
  styles:
    variant: simple
    size: md
    showPageNumbers: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  content:
    previousUrl: "#"
    nextUrl: "#"
    currentPage: 3
    totalPages: 10
  styles:
    showPageNumbers: true

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  previousUrl:
    label: Previous Page URL
    type: url
    comment: URL for the previous page (leave empty to disable)
  nextUrl:
    label: Next Page URL
    type: url
    comment: URL for the next page (leave empty to disable)
  previousLabel:
    label: Previous Button Label
    type: text
  nextLabel:
    label: Next Button Label
    type: text
  currentPage:
    label: Current Page
    type: number
    comment: Current page number (used for display)
  totalPages:
    label: Total Pages
    type: number
    comment: Total number of pages (used for display)
  variant:
    label: Variant
    type: select
    options:
      values:
        - name: Simple (prev/next only)
          id: simple
        - name: With Page Info
          id: with-info
  size:
    label: Size
    type: select
    options:
      values:
        - name: Small
          id: sm
        - name: Medium
          id: md
        - name: Large
          id: lg
  showPageNumbers:
    label: Show Page Numbers
    type: switch
    comment: Display "Page X of Y" between buttons
