# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_sections
  label: "Embed"
  description: Raw HTML embed with aspect ratio options
  icon: code
  tags: [alpha]
  tabbed: true

# Defines the structure of this component, as well as the default values
blueprint:
  _componentId: embed-7ffa46c7-cad1-4731-93a1-9fa8a2c5aad6
  content:
    html:
  styles:
    aspectRatio: landscape

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  html:
    type: code
    label: HTML Code
    comment: Raw HTML content to embed (iframes, widgets, etc.)
    options:
      syntax: html
  aspectRatio:
    type: select
    label: Aspect Ratio
    comment: Container aspect ratio for the embed
    options:
      values:
        - name: Square (1:1)
          id: square
        - name: Landscape (4:3)
          id: landscape
        - name: Portrait (3:4)
          id: portrait
        - name: Widescreen (16:9)
          id: widescreen
