# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_sections
    - editorial_blocks
  label: "Text"
  description: Rich text content block with markdown support
  icon: edit_note
  tags: [alpha]
  tabbed: true

# Defines the structure of this component, as well as the default values
blueprint:
  _componentId: text-5b5d504c-0a73-42df-b117-dfab46bd5360
  content:
    text: >-
      My text goes here. You can use **bold**, *italic*, and [links](https://example.com).
  styles:
    alignX: start

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  text:
    type: markdown
    label: Content
    comment: Rich text content with full markdown support
    options:
      link: true
      blockquote: true
      bold: true
      format: p h2 h3 h4 h5 h6
      italic: true
      strike: true
      subscript: true
      superscript: true
      underline: true
      bulletedlist: true
      numberedlist: true
      code: true
      embed: true
      horizontalrule: true
      image: true
      table: true
      undo: true
      redo: true
      removeformat: true
      copyformatting: true
      snippet: true
  alignX:
    type: choice
    label: Alignment
    comment: Horizontal alignment of the text block
    options:
      allow_empty: false
      value_key: id
      values:
        - name: Start
          id: start
          icon: format_align_left
        - name: Center
          id: center
          icon: format_align_center
        - name: End
          id: end
          icon: format_align_right
