# Metadata about this component, to be used in the CMS
spec:
  structures:
    - mediaCards
  label: "Media Card"
  description:
  icon:
  tags: []
  tabbed: true

# Defines the structure of this component, as well as the default values
blueprint:
  _componentId: defaultMediaCard-4b69bd88-fb9c-4f5e-bc9e-93df0deb3ba1
  content:
    heading: bookshop:generic/heading!
    image: bookshop:generic/image
  styles:
    color_group: primary
    colorFromGroup: background

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
