# Metadata about this component, to be used in the CMS
spec:
  structures:
    - accordion_items
  label: "Accordion Item"
  description: Individual expandable item within an accordion
  icon: expand_more
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  _componentId: accordion-item-79fe257b-fdc1-455f-9ae4-d7e5bfea7a4e
  title: Accordion Item
  contentSections:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  title: Sample Accordion Item
  contentSections:
    - _bookshop_name: building-blocks/core-elements/text
      text: This is the content that appears when the accordion item is expanded.

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  title:
    type: text
    label: Title
    comment: The heading text for this accordion item
  contentSections:
    type: array
    label: Content
    comment: Content sections displayed when this item is expanded
    options:
      structures: _structures.content_sections
