# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Radio Input"
  description: A single radio button input to be used in a radiobutton group
  icon: radio_button_unchecked
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  _componentId: radioInput-7d4ddae1-e19c-41af-8abb-a6a42cd27333
  label: ""
  groupName:
  checked: false
  required: false
  id:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
