# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "DefaultListingCard"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  _componentId: defaultListingCard-6d61377c-cf06-4c1d-8855-1a8ee526691a
  listingTitle: ""
  listingUrl: "#"
  keyInformation: ""
  expires: false
  listingExpiration: "2020-01-01"
  listingTags: ['tag1', 'tag2']
  image: bookshop:generic/image
  color_group: primary
  colorFromGroup: background

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
