# Metadata about this component, to be used in the CMS
spec:
  structures:
    - hero_blocks
  label: "Full Screen Image Text Bottom Hero"
  description:
  icon: feed
  tags: []
  tabbed: true

# Defines the structure of this component, as well as the default values
blueprint:
  _componentId: fullImageTextBottomHero-b0e632cd-24ba-4fdf-b15b-e20780e23c4d
  content:
    sectionId:
    highlightEybrow: false
    eyebrow:
    headline: "Hero Headline"
    description:
    buttons: [bookshop:structure:buttons]
    image: bookshop:structure:imgvid
  styles:
    color_group: primary
    backgroundOpacity: 50

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  image:
    label: Media
  backgroundOpacity:
    type: range
    options:
      min: 0
      max: 100
      step: 5
      default: 50
    comment: Set the opacity percentage of the background
